name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - lsyncd_lua5_3
          - lsyncd_lua5_4
          - lsyncd_lua5_1
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - run: chmod og-rw ~
      - run: nix develop .#${{ matrix.version }} --command ./tests/ci-run.sh
